[package]
name = "controller"
version = "0.1.0"
authors = ["Seth Wright <seth@crosse.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sunray-rs = { path = "../sunray-rs" }
